# Generated by Django 4.1 on 2022-09-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelExample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelexample',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='modelexample',
            name='summary',
            field=models.TextField(),
        ),
    ]
