# Generated by Django 4.1 on 2022-09-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelExample', '0002_alter_modelexample_price_alter_modelexample_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelexample',
            name='feature',
            field=models.BooleanField(null=True),
        ),
    ]
