# Generated by Django 4.1 on 2022-09-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelExample', '0003_modelexample_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelexample',
            name='feature',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
