# Generated by Django 4.1 on 2022-09-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelExample', '0004_alter_modelexample_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelexample',
            name='feature',
        ),
        migrations.AlterField(
            model_name='modelexample',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modelexample',
            name='summary',
            field=models.TextField(default='practice'),
        ),
        migrations.AlterField(
            model_name='modelexample',
            name='title',
            field=models.TextField(),
        ),
    ]
